server:
  port: 0
rocketmq:
  # 多个用;隔开
  name-server: http://117.50.174.141:9876
  producer:
    # 生产组
    group: "demo-group"
    # 发送消息超时时间，默认 3000
    sendMessageTimeout: 3000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 发送异步消息失败重试次数，默认2
    retryTimesWhenSendAsyncFailed: 2