server:
  port: 10012

spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    host: 117.50.174.141
    username: "admin"
    password: "123456"
    virtual-host: demo
    port: 5672
    listener:
      simple:
        # ack 手动答交  若是非手动ACK 那么消息在解析过程中 失败也会认为是被消费的
        acknowledge-mode: manual
        retry:
          enabled: true
          # 重试次数
          max-attempts: 2
          max-interval: 10000   # 重试最大间隔时间
          initial-interval: 2000  # 重试初始间隔时间
          multiplier: 2 # 间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间