server:
  port: 0
rocketmq:
  # 多个用;隔开
  name-server: http://117.50.174.141:9876
#  consumer:
#    # 组
#    group: demo-group
#    # 主体
##    topic:
#    # 批量拉取的数量
#    pull-batch-size: 10
#    # 广播模式 BROADCASTING / 单播 CLUSTERING
#    message-model: "CLUSTERING"