server:
  port: 10001

spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    host: 117.50.174.141
    username: "admin"
    password: "123456"
    virtual-host: demo
    port: 5672
    # 消费者
#    listener:
#      simple:
#        # ack 手动答交
#        acknowledge-mode: manual
    # 生产者
    publisher-confirm-type: correlated
    # 这个开启了，怎么没打印？
    publisher-returns: on
